console.log('📋 Environment Variables Setup Instructions');
console.log('==========================================');
console.log('');
console.log('Please add the following variables to your .env file:');
console.log('');
console.log('RESEND_API_KEY=re_ebJUN9Dx_MuoFb1ubQG2HsUKcte8vezkd');
console.log('NEXT_PUBLIC_APP_URL=http://localhost:3000');
console.log('');
console.log('Your .env file should now contain:');
console.log('• NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY (already present)');
console.log('• CLERK_SECRET_KEY (already present)');
console.log('• DATABASE_URL (already present)');
console.log('• RESEND_API_KEY (add this)');
console.log('• NEXT_PUBLIC_APP_URL (add this)');
console.log('');
console.log('✅ After adding these variables, restart your development server');
console.log('🚀 Then test the order system at: http://localhost:3000/checkout'); 