console.log('📋 Environment Variables Setup Instructions');
console.log('==========================================');
console.log('');
console.log('For LOCAL DEVELOPMENT, add to your .env file:');
console.log('');
console.log('RESEND_API_KEY=your_resend_api_key_here');
console.log('NEXT_PUBLIC_APP_URL=http://localhost:3000');
console.log('');
console.log('For PRODUCTION (ibcedu.com), add to your .env file:');
console.log('');
console.log('RESEND_API_KEY=your_resend_api_key_here');
console.log('NEXT_PUBLIC_APP_URL=https://ibcedu.com');
console.log('');
console.log('Your .env file should now contain:');
console.log('• NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY (already present)');
console.log('• CLERK_SECRET_KEY (already present)');
console.log('• DATABASE_URL (already present)');
console.log('• RESEND_API_KEY (add this)');
console.log('• NEXT_PUBLIC_APP_URL (add this)');
console.log('');
console.log('✅ After adding these variables, restart your development server');
console.log('🚀 Then test the order system at: http://localhost:3000/checkout');
console.log('');
console.log('🌐 For production deployment:');
console.log('1. Update NEXT_PUBLIC_APP_URL to https://ibcedu.com');
console.log('2. Deploy to Vercel/Netlify with your domain');
console.log('3. Update DNS records if needed'); 